name: example
description: 'color_observer_logger example'

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  logging: ^1.2.0
  color_observer_logger: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  color_observer_logger:
    path: ../


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true
