name: color_observer_logger
description: 'color_observer_logger'
version: 0.0.4
homepage: https://pub.dev/packages/color_observer_logger
repository: https://github.com/jack-fan1991/flutter_color_observer_logger
issue_tracker: https://github.com/jack-fan1991/flutter_color_observer_logger/issues

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.2
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
