# .github/workflows/publish.yml
name: Publish to pub.dev

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+*' # tag pattern on pub.dev: 'v'

env:
  flutter_version: "3.10.5"
# Publish using custom workflow
jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Clone Flutter repository with stable channel
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: "stable"
          cache-key: ${{ env.flutter_version }}
      - name: flutter doctor 
        run: flutter doctor -v

      - name: Install dependencies
        run: dart pub get

      - name: Publish
        run: dart pub publish --force